// APIUtilsTypes.js - Tipos de entidades y configuraciones para APIUtils

// Tipos de entidades principales
export const ENTITY_TYPES = {
  CONNECTOR: 'CONNECTOR',
  ROUTING: 'ROUTING',
  MERCHANT_ACCOUNT: 'MERCHANT_ACCOUNT',
  ORGANIZATION_RETRIEVE: 'ORGANIZATION_RETRIEVE',
  REFUNDS: 'REFUNDS',
  REFUND_FILTERS: 'REFUND_FILTERS',
  DISPUTES: 'DISPUTES',
  DISPUTE_FILTERS: 'DISPUTE_FILTERS',
  PAYOUTS: 'PAYOUTS',
  PAYOUTS_FILTERS: 'PAYOUTS_FILTERS',
  ANALYTICS_FILTERS: 'ANALYTICS_FILTERS',
  ANALYTICS_PAYMENTS: 'ANALYTICS_PAYMENTS',
  ANALYTICS_DISPUTES: 'ANALYTICS_DISPUTES',
  ANALYTICS_REFUNDS: 'ANALYTICS_REFUNDS',
  ANALYTICS_AUTHENTICATION: 'ANALYTICS_AUTHENTICATION',
  ANALYTICS_AUTHENTICATION_V2: 'ANALYTICS_AUTHENTICATION_V2',
  ANALYTICS_AUTHENTICATION_V2_FILTERS: 'ANALYTICS_AUTHENTICATION_V2_FILTERS',
  ANALYTICS_ROUTING: 'ANALYTICS_ROUTING',
  API_KEYS: 'API_KEYS',
  ORDERS: 'ORDERS',
  ORDER_FILTERS: 'ORDER_FILTERS',
  ORDERS_AGGREGATE: 'ORDERS_AGGREGATE',
  REFUNDS_AGGREGATE: 'REFUNDS_AGGREGATE',
  DISPUTES_AGGREGATE: 'DISPUTES_AGGREGATE',
  DEFAULT_FALLBACK: 'DEFAULT_FALLBACK',
  SDK_EVENT_LOGS: 'SDK_EVENT_LOGS',
  WEBHOOK_EVENTS: 'WEBHOOK_EVENTS',
  WEBHOOK_EVENTS_ATTEMPTS: 'WEBHOOK_EVENTS_ATTEMPTS',
  WEBHOOKS_EVENTS_RETRY: 'WEBHOOKS_EVENTS_RETRY',
  WEBHOOKS_EVENT_LOGS: 'WEBHOOKS_EVENT_LOGS',
  CONNECTOR_EVENT_LOGS: 'CONNECTOR_EVENT_LOGS',
  ROUTING_EVENT_LOGS: 'ROUTING_EVENT_LOGS',
  GENERATE_SAMPLE_DATA: 'GENERATE_SAMPLE_DATA',
  USERS: 'USERS',
  RECON: 'RECON',
  INTEGRATION_DETAILS: 'INTEGRATION_DETAILS',
  FRAUD_RISK_MANAGEMENT: 'FRAUD_RISK_MANAGEMENT',
  USER_MANAGEMENT: 'USER_MANAGEMENT',
  THREE_DS: 'THREE_DS',
  BUSINESS_PROFILE: 'BUSINESS_PROFILE',
  VERIFY_APPLE_PAY: 'VERIFY_APPLE_PAY',
  PAYMENT_REPORT: 'PAYMENT_REPORT',
  REFUND_REPORT: 'REFUND_REPORT',
  DISPUTE_REPORT: 'DISPUTE_REPORT',
  AUTHENTICATION_REPORT: 'AUTHENTICATION_REPORT',
  PAYPAL_ONBOARDING: 'PAYPAL_ONBOARDING',
  PAYPAL_ONBOARDING_SYNC: 'PAYPAL_ONBOARDING_SYNC',
  ACTION_URL: 'ACTION_URL',
  RESET_TRACKING_ID: 'RESET_TRACKING_ID',
  SURCHARGE: 'SURCHARGE',
  CUSTOMERS: 'CUSTOMERS',
  PAYMENT_METHODS: 'PAYMENT_METHODS',
  PAYMENT_METHODS_DETAILS: 'PAYMENT_METHODS_DETAILS',
  ACCEPT_DISPUTE: 'ACCEPT_DISPUTE',
  DISPUTES_ATTACH_EVIDENCE: 'DISPUTES_ATTACH_EVIDENCE',
  PAYOUT_DEFAULT_FALLBACK: 'PAYOUT_DEFAULT_FALLBACK',
  PAYOUT_ROUTING: 'PAYOUT_ROUTING',
  ACTIVE_PAYOUT_ROUTING: 'ACTIVE_PAYOUT_ROUTING',
  ACTIVE_ROUTING: 'ACTIVE_ROUTING',
  ENABLE_AUTH_RATE_ROUTING: 'ENABLE_AUTH_RATE_ROUTING',
  SET_CONFIG_AUTH_RATE_ROUTING: 'SET_CONFIG_AUTH_RATE_ROUTING',
  ACTIVATE_AUTH_RATE_ROUTING: 'ACTIVATE_AUTH_RATE_ROUTING',
  SET_VOLUME_SPLIT: 'SET_VOLUME_SPLIT',
  GET_VOLUME_SPLIT: 'GET_VOLUME_SPLIT',
  GLOBAL_SEARCH: 'GLOBAL_SEARCH',
  PAYMENT_METHOD_CONFIG: 'PAYMENT_METHOD_CONFIG',
  API_EVENT_LOGS: 'API_EVENT_LOGS',
  ANALYTICS_PAYMENTS_V2: 'ANALYTICS_PAYMENTS_V2',
  ANALYTICS_SANKEY: 'ANALYTICS_SANKEY',
  ANALYTICS_SCA_EXEMPTION_SANKEY: 'ANALYTICS_SCA_EXEMPTION_SANKEY',
  HYPERSENSE: 'HYPERSENSE',
  SIMULATE_INTELLIGENT_ROUTING: 'SIMULATE_INTELLIGENT_ROUTING',
  INTELLIGENT_ROUTING_RECORDS: 'INTELLIGENT_ROUTING_RECORDS',
  INTELLIGENT_ROUTING_GET_STATISTICS: 'INTELLIGENT_ROUTING_GET_STATISTICS',
  SDK_PAYMENT: 'SDK_PAYMENT',
  GET_REVIEW_FIELDS: 'GET_REVIEW_FIELDS',
  TRANSACTION_OVERVIEW: 'TRANSACTION_OVERVIEW',
  RETRY_PERFORMANCE: 'RETRY_PERFORMANCE',
  MONTHLY_RETRY_SUCCESS: 'MONTHLY_RETRY_SUCCESS',
  RETRY_ATTEMPTS_TREND: 'RETRY_ATTEMPTS_TREND',
  ERROR_CATEGORY_ANALYSIS: 'ERROR_CATEGORY_ANALYSIS',
  ACQUIRER_CONFIG_SETTINGS: 'ACQUIRER_CONFIG_SETTINGS',
  RECOVERY_INVOICES: 'RECOVERY_INVOICES',
  RECOVERY_ATTEMPTS: 'RECOVERY_ATTEMPTS',
  THREE_DS_EXEMPTION_RULES: 'THREE_DS_EXEMPTION_RULES',
  HYPERSWITCH_RECON: 'HYPERSWITCH_RECON',
  CHAT_BOT: 'CHAT_BOT'
};

// Tipos de entidades V2
export const V2_ENTITY_TYPES = {
  CUSTOMERS: 'CUSTOMERS',
  V2_CONNECTOR: 'V2_CONNECTOR',
  V2_ATTEMPTS_LIST: 'V2_ATTEMPTS_LIST',
  V2_ORDERS_LIST: 'V2_ORDERS_LIST',
  PAYMENT_METHOD_LIST: 'PAYMENT_METHOD_LIST',
  RETRIEVE_PAYMENT_METHOD: 'RETRIEVE_PAYMENT_METHOD',
  V2_ORDER_FILTERS: 'V2_ORDER_FILTERS',
  V2_ORDERS_AGGREGATE: 'V2_ORDERS_AGGREGATE',
  USERS: 'USERS',
  TOTAL_TOKEN_COUNT: 'TOTAL_TOKEN_COUNT'
};

// Tipos de usuario
export const USER_TYPES = {
  NONE: 'NONE',
  MERCHANT: 'MERCHANT',
  PROFILE: 'PROFILE',
  ORGANIZATION: 'ORGANIZATION'
};

// Tipos de transacción
export const TRANSACTION_ENTITY = {
  MERCHANT: 'Merchant',
  PROFILE: 'Profile',
  ORGANIZATION: 'Organization'
};

// Métodos HTTP
export const HTTP_METHODS = {
  GET: 'GET',
  POST: 'POST',
  PUT: 'PUT',
  DELETE: 'DELETE',
  PATCH: 'PATCH'
};

// Estados de respuesta
export const RESPONSE_STATUS = {
  SUCCESS: 'success',
  ERROR: 'error',
  LOADING: 'loading',
  IDLE: 'idle'
};

// Configuraciones de entorno
export const ENVIRONMENT_CONFIG = {
  SANDBOX: {
    baseUrl: 'https://sandbox.hyperswitch.io',
    apiVersion: 'v1'
  },
  PRODUCTION: {
    baseUrl: 'https://api.hyperswitch.io',
    apiVersion: 'v1'
  }
};

// Configuraciones de timeout
export const TIMEOUT_CONFIG = {
  DEFAULT: 30000,
  LONG_RUNNING: 60000,
  SHORT: 10000
};

// Headers por defecto
export const DEFAULT_HEADERS = {
  'Content-Type': 'application/json',
  'Accept': 'application/json'
};

// Códigos de error comunes
export const ERROR_CODES = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  BAD_REQUEST: 400,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422
};

// Tipos de autenticación
export const AUTH_TYPES = {
  API_KEY: 'api_key',
  JWT: 'jwt',
  OAUTH: 'oauth'
};

export default {
  ENTITY_TYPES,
  V2_ENTITY_TYPES,
  USER_TYPES,
  TRANSACTION_ENTITY,
  HTTP_METHODS,
  RESPONSE_STATUS,
  ENVIRONMENT_CONFIG,
  TIMEOUT_CONFIG,
  DEFAULT_HEADERS,
  ERROR_CODES,
  AUTH_TYPES
};

